# Generated by Django 3.1.2 on 2021-05-21 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User_Info',
            fields=[
                ('id', models.IntegerField(auto_created=True, primary_key=True, serialize=False)),
                ('userId', models.TextField()),
                ('accessToken', models.TextField()),
            ],
        ),
    ]
