# Generated by Django 3.1.2 on 2021-05-21 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('linebotnotify', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_info',
            name='userType',
            field=models.TextField(null=True),
        ),
    ]
