# Generated by Django 3.1.2 on 2021-05-20 08:09

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('apipractice', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='token_key',
            field=models.UUIDField(default=uuid.uuid1),
        ),
        migrations.AlterField(
            model_name='users',
            name='id',
            field=models.IntegerField(auto_created=True, primary_key=True, serialize=False),
        ),
    ]
