# Generated by Django 3.1.2 on 2021-05-20 08:11

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('apipractice', '0002_auto_20210520_0809'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='token_key',
            field=models.UUIDField(default=uuid.uuid4),
        ),
    ]
